### ISSUE TITLE
can't build on a OSX 10.6 Intel 32 bits

### ISSUE THREAD

**Issue by athoune** [brainpicture/node-base64#5]
The build :

```
$ make
node-waf configure build && mkdir -p ~/.node_libraries && cp ./build/default/base64.node ~/.node_libraries/base64.node
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : ok /Users/mlecarme/.node_libraries 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.1.103 
'configure' finished successfully (0.140s)
Waf: Entering directory `/private/tmp/node-base64/build'
Waf: Leaving directory `/private/tmp/node-base64/build'
'build' finished successfully (0.042s)
```

The test :

```
$ make tests
node ./test.js

module:328
  process.dlopen(filename, this.exports);
          ^
Error: dlopen(/private/tmp/node-base64/build/default/base64.node, 1): Symbol not found:    __ZN4node6Buffer20constructor_templateE
  Referenced from: /private/tmp/node-base64/build/default/base64.node
  Expected in: flat namespace
 in /private/tmp/node-base64/build/default/base64.node
    at Module._loadObjectSync (module:328:11)
    at Module.loadSync (module:304:10)
    at loadModule (module:251:12)
    at require (module:374:12)
    at Object.<anonymous> (/private/tmp/node-base64/test.js:1:76)
    at Module._compile (module:426:23)
    at Module._loadScriptSync (module:436:8)
    at Module.loadSync (module:306:10)
    at Object.runMain (module:490:22)
    at node.js:254:10
make: *** [tests] Error 11
```

**Comment by brainpicture** [comment]
Tell me please you version of node
